import Head from "next/head";
import { useEffect, useState } from "react";
import Wallet from "../components/Wallet";

export default function Home() {
  const calculateTimeLeft = () => {
    const event = new Date(Date.UTC(2022, 1, 5, 15, 30, 0));
    let now = new Date();
    const difference =
      +new Date(
        event.toLocaleString("en-US", {
          timeZone: "UTC",
        })
      ) -
      +new Date(
        now.toLocaleString("en-US", {
          timeZone: "UTC",
        })
      );
    let timeLeft = {};
    if (difference > 0) {
      timeLeft = {
        days: Math.floor(difference / (1000 * 60 * 60 * 24)),
        hours: Math.floor((difference / (1000 * 60 * 60)) % 24),
        minutes: Math.floor((difference / 1000 / 60) % 60),
        seconds: Math.floor((difference / 1000) % 60),
      };
    }
    return timeLeft;
  };

  const [timeLeft, setTimeLeft] = useState(calculateTimeLeft());
  useEffect(() => {
    setTimeout(() => {
      setTimeLeft(calculateTimeLeft());
    }, 1000);
  });

  const [account, setAccount] = useState(null);
  const [wallet, setWallet] = useState(false);
  const [balance, setBalance] = useState(0);
  const [disabled, setDisabled] = useState(true);

  useEffect(() => {
    setWallet(false);
  }, [account]);

  const approveDAI = () => {};
  const deposit = () => {};
  const claim = () => {};

  return (
    <div>
      <Head>
        <title>Spartacus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-end w-full mb-10">
        <div className="p-3 space-x-4">
          <button className="px-4 py-2 font-medium transition-all duration-300 rounded bg-slate-100 hover:bg-slate-200">
            {balance === 0
              ? "no balance"
              : Math.round((balance + Number.EPSILON) * 10000) / 10000}
          </button>

          <button
            onClick={() => {
              if (!account) {
                setWallet(true);
              } else {
                setAccount(null);
                setBalance(0);
              }
            }}
            className="px-4 py-2 font-medium transition-all duration-300 rounded bg-slate-100 hover:bg-slate-200"
          >
            {account
              ? `${account.substring(0, 6)}...${account.substring(
                  account.length - 5,
                  account.length
                )}`
              : "Connect Wallet"}
          </button>
          <Wallet
            wallet={wallet}
            setWallet={setWallet}
            setAccount={setAccount}
            setBalance={setBalance}
          />
        </div>
      </div>
      <div className="w-full layout">
        <div className="flex flex-col items-center justify-center w-full">
          <h5 className="mb-6 text-3xl font-semibold md:text-5xl">
            Spartacus (Λ, Λ)
          </h5>
          <h4 className="mb-4">
            Welcome to the Liquidity Bootstrap Event of Spartacus DAO!
          </h4>
          <h4 className="mb-2">
            Our LBE has been a huge success thanks to all of you, Spartacus!
          </h4>
          <h4 className="mb-4">Now claim your SPA.</h4>
          <h4 className="mb-4">
            Remember, let&apos;s (Λ, Λ) together Spartacus!
          </h4>
          <div className="flex items-center justify-center w-full mt-10 space-x-5">
            <button
              onClick={approveDAI}
              disabled={
                !(
                  timeLeft &&
                  Object.keys(timeLeft).length === 0 &&
                  Object.getPrototypeOf(timeLeft) === Object.prototype
                )
              }
              className="px-6 py-2 font-medium transition-all duration-300 bg-pink-200 rounded-lg disabled:bg-pink-100 hover:bg-pink-300"
            >
              Approve DAI
            </button>
            <button
              onClick={deposit}
              disabled={
                !(
                  timeLeft &&
                  Object.keys(timeLeft).length === 0 &&
                  Object.getPrototypeOf(timeLeft) === Object.prototype
                )
              }
              className="px-6 py-2 font-medium transition-all duration-300 bg-pink-200 rounded-lg disabled:bg-pink-100 hover:bg-pink-300"
            >
              Deposit
            </button>
            <button
              onClick={claim}
              // disabled={disabled}
              className="px-6 py-2 font-medium transition-all duration-300 bg-pink-200 rounded-lg disabled:bg-pink-100 hover:bg-pink-300"
            >
              Claim
            </button>
          </div>
          <div className="mt-20">
            Questions? Ask in{" "}
            <a
              className="font-bold"
              href="#"
              target="_blank"
              rel="noopener noreferrer"
            >
              discord
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
